AWSTemplateFormatVersion: '2010-09-09'
Description: Example S3 bucket CloudFormation template
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: example-s3-lab-bucket
